# Generated by Django 5.0.7 on 2024-07-22 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_delete_at_user_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="delete_at",
            new_name="deleted_at",
        ),
    ]
