# Generated by Django 5.0.7 on 2024-07-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_signuptoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signuptoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
